apiVersion: v1
kind: Service
metadata:
  name: "{{  .Chart.Name }}-service"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.servicePort }}
    nodePort: {{ .Values.service.nodePort }}
  - name: https
    port: {{ .Values.service.servicePortHttps }}
  selector:
    app: "{{  .Chart.Name }}-selector"
    
---

apiVersion: v1
kind: Service
metadata:
  name: msbjava3-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 9080
      nodePort: 32366
  selector:
    app: "{{  .Chart.Name }}-selector"
